name: Bug Report
description: Create a bug report for SNPM CLI
labels: 'template: bug'
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: markdown
    attributes:
      value: If you leave out sections there is a high likelihood it will be moved to the GitHub Discussions ["Help" section](https://github.com/vercel/next.js/discussions/categories/help).
  - type: input
    attributes:
      label: Provide installed version
      description: Please provide the current version installed of SNPM by running `npm ls @snpm-io/cli`.
    validations:
      required: true
  - type: input
    attributes:
      label: Current platform
      description: 'For example: Mac OS, Ubuntu, Linux, Windows...'
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    attributes:
      label: Template command (if applicable)
      description: Provide the command to init the template (`snpm create create-next-app`)
    validations:
      required: false
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
