[package]
name = "wasm_links"
version = "0.0.2"
authors = ["nachoaldamav"]
edition = "2021"

[package.metadata.ssvmup.profile.release]
wasm-opt = ['-O4']

[lib]
name = "wasm_links_lib"
path = "src/lib.rs"
crate-type =["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.61"