name: CI Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  platforms:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.11.0
      - name: Install dependencies
        run: pnpm install
      - name: Build CLI
        run: pnpm run build --filter=ultra-pkg
      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1.12.8
      - name: Install CLI
        run: npm install ./packages/cli -g
      - name: Run CI Test
        # Copy examples/ci-test to parent root
        run: cp -r ./examples/ci-test ../ci-test && cd ../ci-test && ultra ci && ultra run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  
  
