name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  platforms:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [19, 18, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.11.0
      - name: Install dependencies
        run: pnpm install
      - name: Build CLI
        run: pnpm run build --filter=ultra-pkg
      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1.12.8
      - name: Install CLI
        run: npm install ./packages/cli -g
      - name: Vite
        run: cd ./examples/vite-demo && ultra test --runs=1
      - name: Next
        run: cd ./examples/next-demo && ultra test --runs=1
      - name: Remix
        run: cd ./examples/remix-demo && ultra test --runs=1
      - name: Turborepo
        run: cd ./examples/monorepo-test && ultra test --runs=1
      
  
  
