name: SNPM CLI Benchmark

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  platforms:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '18'
      - name: Install dependencies
        run: cd packages/cli && npm install
      - name: Build CLI
        run: cd packages/cli && npm run build
      - name: Install CLI
        run: cd packages/cli && npm install . -g && cd ../../
      - name: Run benchmark
        run: cd examples/alotta && snpm benchmark
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Workflow run: ${{ github.run_id }}
      
  
  
