name: SNPM CLI Benchmark

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  platforms:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.11.0
      - name: Install dependencies
        run: pnpm install
      - name: Build CLI
        run: pnpm run build --filter=ultrapkg
      - name: Install CLI
        run: npm install ./packages/cli -g
      - name: Run benchmark
      # Copy examples/alotta to parent root
        run: cp -r ./examples/alotta ../alotta && cd ../alotta && ultra benchmark --ignore-bun --json
      - name: Show JSON
        run: cat ../alotta/results.json
      - name: Read results
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "../alotta/benchmark-results.json"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Benchmark results:
            - OS: ${{ matrix.os }}
            - Node.js: 18
            - Commit: ${{ github.sha }}
            - Pull request title: ${{ github.event.pull_request.title }}

            ${{ steps.read_file.outputs.contents }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  
  
