name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  platforms:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build CLI
        run: npm run build -w=@snpm/cli
      - name: Install CLI
        run: cd packages/cli && npm install . -g && cd ../../
      - name: Create Vite project
        run: npm create vite@latest snpm-vite -- --template react-ts && cd snpm-vite
      - name: Run benchmark
        run: time snpm install
      
  
  
