name: SNPM CLI Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  platforms:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '18'
      - name: Install dependencies
        run: cd packages/cli && npm install
      - name: Build CLI
        run: cd packages/cli && npm run build
      - name: Install CLI
        run: cd packages/cli && npm install . -g && cd ../../
      - name: Run benchmark
        run: cd examples/alotta && snpm benchmark
      
  
  
